required = [
  # replace
  "github.com/golang/gddo/httputil",
  "github.com/mitchellh/mapstructure",

  # generated content
  "github.com/golang/mock/gomock",
  "github.com/golang/mock/mockgen/model",
  "github.com/golang/protobuf/proto",
  "github.com/mailru/easyjson/gen",
  "github.com/mailru/easyjson/jlexer",
  "github.com/mailru/easyjson/jwriter",

  # future deps
  "github.com/ghodss/yaml",
  "github.com/grpc-ecosystem/go-grpc-prometheus",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options",
  "github.com/grpc-ecosystem/grpc-gateway/utilities",
  "golang.org/x/sync/errgroup",
  "google.golang.org/genproto/googleapis/api/annotations",
]

[[constraint]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "^3.3.0"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "^1.5.0"

[[constraint]]
  name = "github.com/kamilsk/go-kit"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/mailru/easyjson"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/rubenv/sql-migrate"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.0"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.13.0"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "^1.3.0"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  non-go = false
  unused-packages = false
