[[constraint]]
  name = "github.com/go-chi/chi"
  version = "^3.3.0"

[[constraint]]
  name = "github.com/golang/gddo"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/kamilsk/go-kit"
  branch = "master"

[[constraint]]
  name = "github.com/mailru/easyjson"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/rubenv/sql-migrate"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "*"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.0"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.13.0"

[[contraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"
